[package]
name = "blog"
version = "0.1.0"
authors = ["Valentin B. <valentin.be@protonmail.com>"]
description = "Source code for my personal blog"
repository = "https://github.com/vbe0201/blog"
homepage = "https://obscure.technology"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
